import Link from "next/link";

export default function TermsOfUse() {
  return (
    <div>
      <div className="mb-4">
        <Link className="text-blue-500 hover:text-blue-700 pt-10 px-6" href="/">
          Go back home
        </Link>
      </div>

      <article className="prose prose-lg p-6">
        <h1 className="text-4xl font-bold text-center">Terms of Use</h1>

        <p>Last updated: March 13, 2023</p>

        <p>
          Please read these terms of use carefully before using Our Service.
        </p>

        <p>Interpretation and Definitions</p>

        <p>
          The words of which the initial letter is capitalized have meanings
          defined under the following conditions. The following definitions
          shall have the same meaning regardless of whether they appear in
          singular or in plural.
        </p>

        <p>Definitions</p>

        <p>For the purposes of these Terms of Use:</p>

        <ul>
          <li>
            Affiliate means an entity that controls, is controlled by or is
            under common control with a party, where `&quot;`control`&quot;`
            means ownership of 50% or more of the shares, equity interest or
            other securities entitled to vote for the election of directors or
            other managing authority.
          </li>

          <li>Country refers to: United States</li>

          <li>
            Company (referred to as either `&quot;`the Company`&quot;`,
            `&quot;`We`&quot;`, `&quot;`Us`&quot;` or `&quot;`Our`&quot;` in
            this Agreement) refers to Customer.io.
          </li>

          <li>
            Device means any device that can access the Service such as a
            computer, a cellphone or a digital tablet.
          </li>

          <li>Service refers to the Website.</li>

          <li>
            Terms of Use (also referred as `&quot;`Terms`&quot;`) mean these
            Terms of Use that form the entire agreement between You and the
            Company regarding the use of the Service. This Terms of Use was
            generated by TermsFeed Terms and Conditions Generator.
          </li>

          <li>
            Third-party Social Media Service means any services or content
            (including data, information, products or services) provided by a
            third-party that may be displayed, included or made available by the
            Service.
          </li>

          <li>Website refers to Customer.io, accessible from customer.io</li>

          <li>
            You means the individual accessing or using the Service, or the
            company, or other legal entity on behalf of which such individual is
            accessing or using the Service, as applicable.
          </li>
        </ul>

        <p>Acknowledgment</p>

        <p>
          These Terms of Use constitute the entire agreement between You and the
          Company regarding the use of the Service and supersede all prior and
          contemporaneous written and oral agreements between You and the
          Company.
        </p>

        <p>
          You may be required to register with the Company in order to access
          certain features of the Service.
        </p>

        <p>By using the Service, You represent and warrant that:</p>

        <ul>
          <li>
            You are of legal age to form a binding contract with the Company;
          </li>

          <li>
            You are not barred to receive services under the laws of the United
            States or other applicable jurisdiction;
          </li>

          <li>
            You are using the Service only for Your own personal use, and not
            for the benefit of any third party;
          </li>

          <li>
            You will not use the Service to commit any harmful or illegal
            activities;
          </li>

          <li>
            Your use of the Service will comply with these Terms of Use and all
            applicable local, national and international laws and regulations.
          </li>
        </ul>

        <p>
          If You do not agree with all of these Terms of Use, then You are
          prohibited from using the Service and You must destroy all copies of
          the materials You have obtained from the Service.
        </p>

        <p>
          Your use of the Service is at Your sole risk. The Service is provided
          on an `&quot;`AS IS`&quot;` and `&quot;`AS AVAILABLE`&quot;` basis.
          The Service is provided without warranties of any kind, whether
          express or implied, including, but not limited to, implied warranties
          of merchantability, fitness for a particular purpose, non-infringement
          or course of performance.
        </p>

        <p>
          The Company its subsidiaries, affiliates, and its licensors do not
          warrant that a) the Service will function uninterrupted, secure or
          available at any particular time or location; b) any errors or defects
          will be corrected; c) the Service is free of viruses or other harmful
          components; or d) the results of using the Service will meet Your
          requirements.
        </p>

        <p>
          In no event will the Company, nor its directors, employees, partners,
          agents, suppliers, or affiliates, be liable for any indirect,
          incidental, special, consequential or punitive damages, including
          without limitation, loss of profits, data, use, goodwill, or other
          intangible losses, resulting from (i) Your access to or use of or
          inability to access or use the Service; (ii) any conduct or content of
          any third party on the Service; (iii) any content obtained from the
          Service; and (iv) unauthorized access, use or alteration of Your
          transmissions or content, whether based on warranty, contract, tort
          (including negligence) or any other legal theory, whether or not the
          Company has been informed of the possibility of such damages, and even
          if a remedy set forth herein is found to have failed of its essential
          purpose.
        </p>

        <p>
          The Company its subsidiaries, affiliates, and its licensors do not
          warrant that a) the Service will function uninterrupted, secure or
          available at any particular time or location; b) any errors or defects
          will be corrected; c) the Service is free of viruses or other harmful
          components; or d) the results of using the Service will meet Your
          requirements.
        </p>

        <p>
          In no event will the Company, nor its directors, employees, partners,
          agents, suppliers, or affiliates, be liable for any indirect,
          incidental, special, consequential or punitive damages, including
          without limitation, loss of profits, data, use, goodwill, or other
          intangible losses, resulting from (i) Your access to or use of or
          inability to access or use the Service; (ii) any conduct or content of
          any third party on the Service; (iii) any content obtained from the
          Service; and (iv) unauthorized access, use or alteration of Your
          transmissions or content, whether based on warranty, contract, tort
          (including negligence) or any other legal theory, whether or not the
          Company has been informed of the possibility of such damages, and even
          if a remedy set forth herein is found to have failed of its essential
          purpose.
        </p>

        <p>
          We reserve the right, at Our sole discretion, to modify or replace
          these Terms of Use at any time. If a revision is material We will try
          to provide at least 30 days notice prior to any new terms taking
          effect. What constitutes a material change will be determined at Our
          sole discretion.
        </p>

        <p>
          By continuing to access or use Our Service after those revisions
          become effective, You agree to be bound by the revised terms. If You
          do not agree to the new terms, You must stop using the Service.
        </p>

        <p>Please review this Agreement carefully.</p>

        <p>
          By using the Service or by executing a document that references this
          Agreement, You consent to be bound by this Agreement.
        </p>

        <p>
          If You disagree with any of the terms of this Agreement, You must not
          use the Service.
        </p>

        <p>Contact Us</p>

        <p>
          If You have any questions about these Terms of Use, You can contact
          us:
        </p>

        <ul>
          <li>By email: hello@customer.io</li>
        </ul>
      </article>
    </div>
  );
}
